# Generated by Django 4.0 on 2022-04-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MechineTestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freg',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
