# Generated by Django 4.0 on 2022-04-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MechineTestapp', '0003_rename_address_freg_adrs_rename_fname_freg_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freg',
            name='adrs',
        ),
        migrations.RemoveField(
            model_name='freg',
            name='img',
        ),
        migrations.RemoveField(
            model_name='freg',
            name='location',
        ),
        migrations.RemoveField(
            model_name='freg',
            name='number',
        ),
    ]
