# Generated by Django 4.0 on 2022-04-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MechineTestapp', '0004_remove_freg_adrs_remove_freg_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freg',
            old_name='uname',
            new_name='username',
        ),
    ]
