# Generated by Django 4.0 on 2022-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MechineTestapp', '0005_rename_uname_freg_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=200, null=True)),
                ('Lname', models.CharField(max_length=200, null=True)),
                ('date', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('number', models.IntegerField(null=True)),
                ('adrs', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
