# Generated by Django 4.0 on 2022-04-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MechineTestapp', '0008_creg_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creg',
            old_name='status',
            new_name='year',
        ),
        migrations.AddField(
            model_name='creg',
            name='month',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
